version: '5.0'

actions:

  dataset_death_raw:
    run: ehrql:v1 generate-dataset analysis/dataset_def/dataset_definition.py 
      --output output/highly_sensitive/dataset_death_TPP_ONS.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/highly_sensitive/dataset_death_TPP_ONS.csv.gz

  dataset_death_processed:
    run: r:v2 analysis/1_derive_key_variables.R 
    needs: [dataset_death_raw]
    outputs:
      highly_sensitive:
        csv: output/highly_sensitive/death_registration_processed.csv.gz
      moderately_sensitive:
        txt: output/analysis_tables/death_registration_processed_skim.txt
        csv: output/analysis_tables/table_source_raw.csv


  report_implausible_death_dates:
    run: r:v2 analysis/2_implausible_death_dates.R 
    needs: [dataset_death_processed]
    outputs:
      moderately_sensitive:
        death_implausible_source: output/analysis_tables/death_implausible_source.csv

  report_registration_at_death:
    run: r:v2 analysis/3_registration_at_death.R 
    needs: [dataset_death_processed]
    outputs:
      moderately_sensitive:
        registration_status_source: output/analysis_tables/registration_status_source.csv 
        reg_start_timing_source: output/analysis_tables/reg_start_timing_source.csv
        reg_end_timing_source: output/analysis_tables/reg_end_timing_source.csv

  report_death_source_comparison:
    run: r:v2 analysis/4_death_source_comparison.R 
    needs: [dataset_death_processed]
    outputs:
      moderately_sensitive:
        table_death_source: output/analysis_tables/table_death_source.csv
        table_death_source_25_26: output/analysis_tables/table_death_source_25_26.csv
        tpp_death_code_or_date: output/analysis_tables/tpp_death_code_or_date.csv
        table_death_source_overall_any_tpp: output/analysis_tables/table_death_source_any_tpp.csv

  report_sources_date_agreement:
    run: r:v2 analysis/5_sources_date_agreement.R 
    needs: [dataset_death_processed]
    outputs:
      moderately_sensitive:
        table_ons_tpp_dates_diff: output/analysis_tables/table_ons_tpp_dates_diff.csv
  
  report_variation_source_by_practice:
    run: r:v2 analysis/6_variation_source_by_practice.R 
    needs: [dataset_death_processed]
    outputs:
      moderately_sensitive:
        table_practice_percentiles: output/analysis_tables/table_practice_percentiles.csv
  
# end---- 
