version: '4.0'

actions:
#Dataset for diff time
  dataset_death_date_diff:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/dataset_death_date_diff.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_death_date_diff.csv.gz
  
  summary_stat:
    run: r:v2 analysis/summary_stats.R
      --output output/DoD/summary_stats_DoD.csv 
    needs: [dataset_death_date_diff]
    outputs:
      moderately_sensitive:
        csv: output/DoD/summary_stats_DoD.csv




# Measures
  measures_overall:
    run: ehrql:v1 generate-measures analysis/measure_def.py 
      --output output/measures/measures_overall.csv
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_overall.csv

  measures_by_practice:
    run: ehrql:v1 generate-measures analysis/measures_practice.py 
      --output output/measures/measures_by_practice.csv
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_by_practice.csv