version: '4.0'

actions:
#Dataset for diff time
  dataset_death_date_diff:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/dataset_death_date_diff.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_death_date_diff.csv.gz
  
  summary_stat:
    run: r:v2 analysis/summary_stats.R
      --output output/DoD/summary_stats_DoD.csv 
    needs: [dataset_death_date_diff]
    outputs:
      moderately_sensitive:
        continuous: output/DoD/summary_stats_DoD.csv
        categorical: output/DoD/table_freq_DoD.csv

  table_DoD:
    run: r:v2 analysis/Table_DoD.R
      --output output/report/*.csv 
    needs: [dataset_death_date_diff]
    outputs:
      moderately_sensitive:
        categorical1: output/report/collate_death_source_table.csv
        categorical2: output/report/collate_DoD_diff_table.csv
        categorical3: output/report/collate_death_source_table_spec_periods.csv

  visualization:
    run:  r:v2 Final-visualizations.R
    needs: [table_DoD]
    outputs:
      moderately_sensitive:
        csv: output/final_visualization/*.csv
        png: output/final_visualization/*.png 

# Measures
  measures_overall:
    run: ehrql:v1 generate-measures analysis/measure_def.py 
      --output output/measures/measures_overall.csv
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measures_overall.csv
  
  table_measure_rate:
    run: r:v2 analysis/Table_measure_rate.R
      --output output/report/*.csv 
    needs: [measures_overall]
    outputs:
      moderately_sensitive:
        categorical: output/report/collate_measures_rate_table.csv

  measures_by_practice:
    run: ehrql:v1 generate-measures analysis/measure_practice.py 
      --output output/measures/measures_by_practice.csv
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_by_practice.csv

