version: '4.0'

actions:
  dataset_def:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/dataset_death.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_death.csv.gz

